"""
reporting.py — Output generation and logging for UdaciScan.
 
Responsibilities:
  - save_json()     : serialize a RepurposingBrief to outputs/brief_<Disease>.json
  - save_markdown() : render a human-readable brief to outputs/brief_<Disease>.md
  - log_step()      : append a structured entry to runs/trace_<timestamp>.jsonl
"""
 
from __future__ import annotations
 
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional
 
from schema import CandidateDrug, RepurposingBrief
 
 
# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------
 
def _safe_filename(name: str) -> str:
    """Turn a disease name into a safe filename fragment (no spaces/special chars)."""
    return re.sub(r"[^a-zA-Z0-9_-]", "_", name.strip())
 
 
def _ensure_dir(path: str) -> Path:
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    return p
 
 
# ---------------------------------------------------------------------------
# JSON output
# ---------------------------------------------------------------------------
 
def save_json(brief: RepurposingBrief, output_dir: str = "outputs") -> Path:
    """
    Serialize a RepurposingBrief to JSON and write it to:
        <output_dir>/brief_<Disease>.json
 
    The file validates against the Pydantic schema by construction.
 
    Args:
        brief:      A fully populated RepurposingBrief instance.
        output_dir: Directory where the file will be written (created if absent).
 
    Returns:
        Path to the written file.
    """
    _ensure_dir(output_dir)
    filename = f"brief_{_safe_filename(brief.disease)}.json"
    out_path = Path(output_dir) / filename
 
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(brief.model_dump_json(indent=2))
 
    print(f"[reporting] JSON saved -> {os.path.relpath(out_path)}")
    return out_path
 
 
# ---------------------------------------------------------------------------
# Markdown output
# ---------------------------------------------------------------------------
 
def _tier_badge(tier: str) -> str:
    badges = {
        "phase-3":     "Phase 3",
        "phase-2":     "Phase 2",
        "phase-1":     "Phase 1",
        "preclinical": "Preclinical",
    }
    return badges.get(tier, tier)
 
 
def _render_candidate(rank: int, c: CandidateDrug) -> str:
    pmid_links = ", ".join(
        f"[PMID:{p}](https://pubmed.ncbi.nlm.nih.gov/{p}/)" for p in c.pmids
    )
    mechanism_terms = ", ".join(c.mechanism_terms) if c.mechanism_terms else "—"
 
    return (
        f"### {rank}. {c.drug_name}\n\n"
        f"| Field | Value |\n"
        f"|---|---|\n"
        f"| **Evidence tier** | {_tier_badge(c.evidence_tier)} |\n"
        f"| **Study model** | {c.model} |\n"
        f"| **Outcome** | {c.outcome} |\n"
        f"| **Score** | {c.score:.3f} |\n"
        f"| **Extractor confidence** | {c.confidence:.2f} |\n\n"
        f"**Mechanism hypothesis:** {c.mechanism_hypothesis}\n\n"
        f"**Rationale:** {c.rationale}\n\n"
        f"**Mechanism terms:** {mechanism_terms}\n\n"
        f"**Citations:** {pmid_links}\n"
    )
 
 
def save_markdown(brief: RepurposingBrief, output_dir: str = "outputs") -> Path:
    """
    Render a RepurposingBrief to a human-readable Markdown file:
        <output_dir>/brief_<Disease>.md
 
    Structure:
        - Header (disease, date, method summary)
        - Ranked candidates (mechanism, rationale, tier, score, PMIDs)
        - Limitations
 
    Args:
        brief:      A fully populated RepurposingBrief instance.
        output_dir: Directory where the file will be written (created if absent).
 
    Returns:
        Path to the written file.
    """
    _ensure_dir(output_dir)
    filename = f"brief_{_safe_filename(brief.disease)}.md"
    out_path = Path(output_dir) / filename
 
    lines = [
        f"# UdaciScan — Drug Repurposing Brief",
        f"",
        f"**Disease:** {brief.disease}",
        f"**Date:** {brief.date}",
        f"",
        f"## Method Summary",
        f"",
        brief.method_summary,
        f"",
        f"---",
        f"",
        f"## Ranked Repurposing Candidates",
        f"",
    ]
 
    if not brief.candidates:
        lines.append("_No candidates found for this query._\n")
    else:
        for rank, candidate in enumerate(brief.candidates, start=1):
            lines.append(_render_candidate(rank, candidate))
            lines.append("---\n")
 
    lines += [
        f"## Limitations",
        f"",
        brief.limitations,
        f"",
        f"---",
        f"",
        f"_This report is generated by UdaciScan for research purposes only "
        f"and does not constitute medical advice._",
    ]
 
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
 
    print(f"[reporting] Markdown saved -> {os.path.relpath(out_path)}")
    return out_path
 
 
# ---------------------------------------------------------------------------
# Trajectory logging (JSONL)
# ---------------------------------------------------------------------------
 
def log_step(
    trace_path: str,
    step: str,
    params: Optional[Dict[str, Any]] = None,
    result: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Append a single structured step entry to a JSONL trace file.
 
    Each line is a self-contained JSON object with:
        - timestamp  : ISO 8601 UTC
        - step       : name of the agent step (e.g. "retrieve", "evaluate", ...)
        - params     : input parameters for this step
        - result     : key outputs / metrics from this step
 
    Args:
        trace_path: Path to the .jsonl file (created if absent).
        step:       Step name — one of: retrieve, evaluate, live_fetch,
                    requery, rerank, extract, score, synthesize.
        params:     Dict of input parameters (k, tau, n, query, ...).
        result:     Dict of outputs (n_docs, confidence, n_candidates, ...).
    """
    _ensure_dir(str(Path(trace_path).parent))
 
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "step":      step,
        "params":    params or {},
        "result":    result or {},
    }
 
    with open(trace_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
 
 
def make_trace_path(runs_dir: str = "runs") -> str:
    """
    Build a timestamped trace file path:
        <runs_dir>/trace_<YYYYMMDD_HHMMSS>.jsonl
 
    Args:
        runs_dir: Directory where trace files are stored (created if absent).
 
    Returns:
        Full path string (file not yet created).
    """
    _ensure_dir(runs_dir)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return str(Path(runs_dir) / f"trace_{ts}.jsonl")